import { useMemo, useState } from "react";
import type { Customer, DisplayCurrency, Invoice, PaymentIntent, PaymentLink, WebhookDelivery } from "./lib/types";
import { formatDisplay, parseDecimal } from "./lib/money";

type Screen = "home" | "payments" | "customers" | "invoices" | "links" | "analytics" | "webhooks" | "settings" | "checkout";

type Ledger = {
  organization: { name: string; environment: "sandbox" | "live"; displayCurrency: DisplayCurrency; settlementAsset: string; settlementWallet: string; acceptedAssets: string[] };
  intents: PaymentIntent[];
  customers: Customer[];
  invoices: Invoice[];
  links: PaymentLink[];
  deliveries: WebhookDelivery[];
};

const now = new Date();
const iso = (offset: number) => new Date(now.getTime() - offset * 86400000).toISOString();
const seed: Ledger = {
  organization: { name: "Northwind Labs", environment: "sandbox", displayCurrency: "USD", settlementAsset: "USDC", settlementWallet: "7xK...mP2", acceptedAssets: ["USDC", "SOL", "USDT"] },
  intents: [
    { id: "pi_8QmK2", status: "confirmed", amount: "1290.00", amountMinor: "129000", currency: "USD", acceptedAssets: ["USDC", "SOL"], settlementAsset: "USDC", description: "Annual Pro plan", customerName: "Olivia Chen", customerEmail: "olivia@example.com", reference: "ORD-1048", recipient: "7xK...mP2", network: "sandbox", paidAsset: "USDC", paidRaw: "1290000000", signature: "5d9...a7f", recovery: null, createdAt: iso(0), confirmedAt: iso(0), checkoutUrl: "/checkout/pi_8QmK2" },
    { id: "pi_8QmK1", status: "pending", amount: "480.00", amountMinor: "48000", currency: "USD", acceptedAssets: ["USDC", "SOL"], settlementAsset: "USDC", description: "Design retainer", customerName: "Studio Lumen", customerEmail: "finance@lumen.co", reference: "INV-204", recipient: "7xK...mP2", network: "sandbox", paidAsset: null, paidRaw: null, signature: null, recovery: null, createdAt: iso(1), confirmedAt: null, checkoutUrl: "/checkout/pi_8QmK1" },
    { id: "pi_8QmJ9", status: "confirmed", amount: "860.00", amountMinor: "86000", currency: "USD", acceptedAssets: ["USDC", "SOL"], settlementAsset: "USDC", description: "API usage", customerName: "Maya Patel", customerEmail: "maya@example.com", reference: "ORD-1041", recipient: "7xK...mP2", network: "sandbox", paidAsset: "SOL", paidRaw: "5200000000", signature: "3bc...19e", recovery: null, createdAt: iso(3), confirmedAt: iso(3), checkoutUrl: "/checkout/pi_8QmJ9" },
    { id: "pi_8QmJ8", status: "failed", amount: "220.00", amountMinor: "22000", currency: "USD", acceptedAssets: ["USDC"], settlementAsset: "USDC", description: "Starter plan", customerName: "Acme Inc.", customerEmail: "pay@acme.co", reference: "ORD-1038", recipient: "7xK...mP2", network: "sandbox", paidAsset: null, paidRaw: null, signature: null, recovery: { kind: "underpaid", receivedDisplay: "$180.00", requiredDisplay: "$220.00", remainingDisplay: "$40.00", message: "Payment received below the requested amount." }, createdAt: iso(5), confirmedAt: null, checkoutUrl: "/checkout/pi_8QmJ8" },
  ],
  customers: [
    { id: "cus_01", name: "Olivia Chen", email: "olivia@example.com", totalPaidMinor: "129000", paymentCount: 1, lastPaymentAt: iso(0) },
    { id: "cus_02", name: "Maya Patel", email: "maya@example.com", totalPaidMinor: "86000", paymentCount: 1, lastPaymentAt: iso(3) },
    { id: "cus_03", name: "Studio Lumen", email: "finance@lumen.co", totalPaidMinor: "0", paymentCount: 0, lastPaymentAt: null },
  ],
  invoices: [{ id: "in_001", number: "INV-204", status: "open", customerName: "Studio Lumen", currency: "USD", totalMinor: "48000", dueDate: "2026-09-20", paymentIntentId: "pi_8QmK1", items: [{ description: "Design retainer", quantity: "1", amountMinor: "48000" }] }],
  links: [{ id: "plink_01", amount: "1290.00", amountMinor: "129000", currency: "USD", description: "Annual Pro plan", acceptedAssets: ["USDC", "SOL"], active: true, intentId: "pi_8QmK2", createdAt: iso(0) }],
  deliveries: [{ id: "evt_01", eventType: "payment.confirmed", success: true, statusCode: 200, createdAt: iso(0) }, { id: "evt_02", eventType: "payment.created", success: true, statusCode: 200, createdAt: iso(1) }, { id: "evt_03", eventType: "payment.failed", success: false, statusCode: 500, createdAt: iso(5) }],
};

const nav: { id: Screen; label: string; icon: string }[] = [
  { id: "home", label: "Overview", icon: "⌂" }, { id: "payments", label: "Payments", icon: "↔" }, { id: "customers", label: "Customers", icon: "○" }, { id: "invoices", label: "Invoices", icon: "▤" }, { id: "links", label: "Payment links", icon: "↗" }, { id: "analytics", label: "Analytics", icon: "⌁" }, { id: "webhooks", label: "Webhooks", icon: "◌" }, { id: "settings", label: "Settings", icon: "⚙" },
];

function money(minor: string, currency = "USD") { return formatDisplay(BigInt(minor), currency, 2); }
function shortDate(value: string | null) { return value ? new Date(value).toLocaleDateString("en-US", { month: "short", day: "numeric" }) : "—"; }
function statusClass(status: string) { return `status status-${status.replaceAll("_", "-")}`; }

export default function App() {
  const [screen, setScreen] = useState<Screen>("home");
  const [ledger, setLedger] = useState(seed);
  const [menuOpen, setMenuOpen] = useState(false);
  const [toast, setToast] = useState("");
  const [selectedIntent, setSelectedIntent] = useState<PaymentIntent | null>(null);
  const [modal, setModal] = useState<"payment" | "invoice" | "link" | null>(null);
  const [form, setForm] = useState({ amount: "", description: "", customer: "", email: "" });
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const go = (next: Screen) => { setScreen(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const total = useMemo(() => ledger.intents.filter((i) => i.status === "confirmed" || i.status === "settled").reduce((sum, i) => sum + BigInt(i.amountMinor), 0n).toString(), [ledger]);
  const createPayment = () => {
    if (!form.amount || Number(form.amount) <= 0) return showToast("Enter a valid amount");
    const minor = parseDecimal(form.amount, 2).toString();
    const intent: PaymentIntent = { id: `pi_${Math.random().toString(36).slice(2, 8)}`, status: "pending", amount: form.amount, amountMinor: minor, currency: "USD", acceptedAssets: ledger.organization.acceptedAssets, settlementAsset: "USDC", description: form.description || "Payment", customerName: form.customer || null, customerEmail: form.email || null, reference: `ORD-${Math.floor(1000 + Math.random() * 8999)}`, recipient: ledger.organization.settlementWallet, network: "sandbox", paidAsset: null, paidRaw: null, signature: null, recovery: null, createdAt: new Date().toISOString(), confirmedAt: null, checkoutUrl: `/checkout/pi_${Math.random().toString(36).slice(2, 8)}` };
    setLedger((current) => ({ ...current, intents: [intent, ...current.intents] })); setModal(null); setForm({ amount: "", description: "", customer: "", email: "" }); showToast("Payment intent created"); setSelectedIntent(intent); go("payments");
  };
  const simulatePayment = (intent: PaymentIntent) => { const updated = { ...intent, status: "confirmed" as const, paidAsset: "USDC", signature: "sim..." + Math.random().toString(36).slice(2, 6), confirmedAt: new Date().toISOString() }; setLedger((current) => ({ ...current, intents: current.intents.map((item) => item.id === intent.id ? updated : item) })); setSelectedIntent(updated); showToast("Payment confirmed in sandbox"); };

  if (screen === "checkout" && selectedIntent) return <Checkout intent={selectedIntent} onBack={() => go("payments")} onPay={() => simulatePayment(selectedIntent)} />;
  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={() => go("home")}><span className="brand-mark">S</span><span>SwanPay</span></button><div className="top-actions"><button className="env-pill" onClick={() => showToast("Sandbox environment is active")}>Sandbox <span className="dot" /></button><button className="avatar" onClick={() => go("settings")}>N</button><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open navigation">☰</button></div></header>
    <div className="layout"><aside className={menuOpen ? "sidebar open" : "sidebar"}><div className="workspace"><span className="workspace-icon">N</span><span><strong>{ledger.organization.name}</strong><small>Workspace</small></span><span className="chevron">⌄</span></div><nav>{nav.map((item) => <button key={item.id} className={screen === item.id ? "nav-item active" : "nav-item"} onClick={() => go(item.id)}><span className="nav-icon">{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => showToast("Help center opened")}><span className="nav-icon">?</span>Help & docs</button><button className="user-row" onClick={() => go("settings")}><span className="avatar small">N</span><span><strong>Nora Adams</strong><small>Owner</small></span><span>⋮</span></button></div></aside><main className="main-content">{screen === "home" && <Overview total={total} ledger={ledger} onNavigate={go} onCreate={() => setModal("payment")} onSelect={(intent) => { setSelectedIntent(intent); go("payments"); }} />}{screen === "payments" && <Payments ledger={ledger} onCreate={() => setModal("payment")} onCheckout={(intent) => { setSelectedIntent(intent); go("checkout"); }} onSelect={setSelectedIntent} />}{screen === "customers" && <Customers ledger={ledger} />}{screen === "invoices" && <Invoices ledger={ledger} onCreate={() => setModal("invoice")} onPay={(intentId) => { const intent = ledger.intents.find((item) => item.id === intentId); if (intent) { setSelectedIntent(intent); go("checkout"); } }} />}{screen === "links" && <Links ledger={ledger} onCreate={() => setModal("link")} onCopy={() => showToast("Payment link copied")} />}{screen === "analytics" && <Analytics ledger={ledger} />}{screen === "webhooks" && <Webhooks ledger={ledger} onTest={() => showToast("Test event delivered successfully")} />}{screen === "settings" && <Settings ledger={ledger} setLedger={setLedger} onSave={() => showToast("Settings saved")} />}</main></div>
    {modal && <Modal title={modal === "payment" ? "Create payment" : modal === "invoice" ? "Create invoice" : "Create payment link"} onClose={() => setModal(null)}><div className="form-grid"><label>Amount<input inputMode="decimal" placeholder="0.00" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>Description<input placeholder="What is this for?" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Customer name<input placeholder="Optional" value={form.customer} onChange={(e) => setForm({ ...form, customer: e.target.value })} /></label><label>Customer email<input type="email" placeholder="Optional" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label></div><button className="primary full" onClick={createPayment}>{modal === "payment" ? "Create payment intent" : modal === "invoice" ? "Create invoice" : "Create link"}</button></Modal>}
    {toast && <div className="toast">{toast}</div>}
  </div>;
}

function PageHeader({ eyebrow, title, description, action, onAction }: { eyebrow?: string; title: string; description?: string; action?: string; onAction?: () => void }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow || "Workspace"}</p><h1>{title}</h1>{description && <p className="page-description">{description}</p>}</div>{action && <button className="primary" onClick={onAction}>{action}</button>}</div>; }
function Overview({ total, ledger, onNavigate, onCreate, onSelect }: { total: string; ledger: Ledger; onNavigate: (s: Screen) => void; onCreate: () => void; onSelect: (i: PaymentIntent) => void }) { return <><PageHeader eyebrow="Tuesday, September 8" title="Good morning, Nora" description="Here is what is happening with your payments." action="Create payment" onAction={onCreate} /><section className="stats-grid"><Stat label="Total volume" value={money(total)} trend="+18.4%" /><Stat label="Successful payments" value={String(ledger.intents.filter((i) => i.status === "confirmed").length)} trend="+12.0%" /><Stat label="Pending" value={String(ledger.intents.filter((i) => i.status === "pending").length)} trend="Needs review" muted /></section><div className="content-grid"><section className="card chart-card"><div className="card-heading"><div><h2>Payment volume</h2><p>Last 30 days</p></div><select><option>30 days</option><option>7 days</option></select></div><div className="chart"><div className="chart-labels"><span>$3k</span><span>$2k</span><span>$1k</span><span>$0</span></div><div className="chart-area"><div className="chart-line" /><div className="chart-bars">{[28,42,34,56,48,67,52,74,62,82,68,91].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div></div></div><div className="chart-legend"><span><i className="legend-dot purple" />Volume</span><span><i className="legend-dot cyan" />Successful</span></div></section><section className="card activity-card"><div className="card-heading"><div><h2>Recent activity</h2><p>Latest payment events</p></div><button className="text-button" onClick={() => onNavigate("payments")}>View all</button></div><div className="activity-list">{ledger.intents.slice(0, 4).map((intent) => <button className="activity-row" key={intent.id} onClick={() => onSelect(intent)}><span className={intent.status === "confirmed" ? "activity-icon success" : intent.status === "failed" ? "activity-icon danger" : "activity-icon pending"}>{intent.status === "confirmed" ? "✓" : intent.status === "failed" ? "!" : "…"}</span><span className="activity-copy"><strong>{intent.description}</strong><small>{intent.customerName || "Unknown customer"} · {shortDate(intent.createdAt)}</small></span><strong>{money(intent.amountMinor)}</strong></button>)}</div></section></div><section className="card quick-card"><div><span className="quick-icon">↗</span><div><h2>Accept your first payment</h2><p>Share a payment link or integrate the API to start collecting.</p></div></div><div className="quick-actions"><button className="secondary" onClick={() => onNavigate("links")}>Create payment link</button><button className="secondary" onClick={() => onNavigate("checkout")}>View docs</button></div></section></>; }
function Stat({ label, value, trend, muted }: { label: string; value: string; trend: string; muted?: boolean }) { return <div className="card stat-card"><p>{label}</p><strong>{value}</strong><span className={muted ? "trend muted" : "trend"}>{trend}</span></div>; }
function Payments({ ledger, onCreate, onCheckout, onSelect }: { ledger: Ledger; onCreate: () => void; onCheckout: (i: PaymentIntent) => void; onSelect: (i: PaymentIntent) => void }) { const [filter, setFilter] = useState("all"); const rows = ledger.intents.filter((i) => filter === "all" || i.status === filter); return <><PageHeader title="Payments" description="Track, manage, and reconcile every payment." action="Create payment" onAction={onCreate} /><div className="toolbar"><div className="tabs">{["all", "confirmed", "pending", "failed"].map((item) => <button className={filter === item ? "tab active" : "tab"} onClick={() => setFilter(item)} key={item}>{item === "all" ? "All payments" : item[0].toUpperCase() + item.slice(1)} <span>{item === "all" ? ledger.intents.length : ledger.intents.filter((i) => i.status === item).length}</span></button>)}</div><input className="search" placeholder="Search payments" /></div><div className="card table-card"><div className="table-wrap"><table><thead><tr><th>Payment</th><th>Customer</th><th>Status</th><th>Amount</th><th>Date</th><th /></tr></thead><tbody>{rows.map((intent) => <tr key={intent.id} onClick={() => onSelect(intent)}><td><strong>{intent.id}</strong><small>{intent.description}</small></td><td>{intent.customerName || "—"}</td><td><span className={statusClass(intent.status)}>{intent.status.replaceAll("_", " ")}</span></td><td><strong>{money(intent.amountMinor)}</strong><small>{intent.paidAsset || intent.settlementAsset}</small></td><td>{shortDate(intent.createdAt)}</td><td><button className="row-action" onClick={(e) => { e.stopPropagation(); onCheckout(intent); }}>Open</button></td></tr>)}</tbody></table></div></div></>; }
function Customers({ ledger }: { ledger: Ledger }) { return <><PageHeader title="Customers" description="Your customer directory and payment history." action="Add customer" /><div className="card table-card"><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Total paid</th><th>Payments</th><th>Last payment</th></tr></thead><tbody>{ledger.customers.map((customer) => <tr key={customer.id}><td><div className="customer-cell"><span className="avatar customer-avatar">{customer.name.slice(0, 1)}</span><span><strong>{customer.name}</strong><small>{customer.email || "No email"}</small></span></div></td><td>{money(customer.totalPaidMinor)}</td><td>{customer.paymentCount}</td><td>{shortDate(customer.lastPaymentAt)}</td></tr>)}</tbody></table></div></div></>; }
function Invoices({ ledger, onCreate, onPay }: { ledger: Ledger; onCreate: () => void; onPay: (id: string) => void }) { return <><PageHeader title="Invoices" description="Send invoices and get paid on time." action="Create invoice" onAction={onCreate} /><div className="invoice-grid">{ledger.invoices.map((invoice) => <div className="card invoice-card" key={invoice.id}><div className="invoice-top"><span className="invoice-icon">▤</span><span className={statusClass(invoice.status)}>{invoice.status}</span></div><p className="eyebrow">{invoice.number}</p><h2>{money(invoice.totalMinor, invoice.currency)}</h2><p>{invoice.customerName}</p><div className="invoice-meta"><span>Due {shortDate(invoice.dueDate)}</span><button className="text-button" onClick={() => invoice.paymentIntentId && onPay(invoice.paymentIntentId)}>View invoice</button></div></div>)}</div></>; }
function Links({ ledger, onCreate, onCopy }: { ledger: Ledger; onCreate: () => void; onCopy: () => void }) { return <><PageHeader title="Payment links" description="Reusable links for products, plans, and donations." action="Create link" onAction={onCreate} /><div className="link-list">{ledger.links.map((link) => <div className="card link-card" key={link.id}><div className="link-icon">↗</div><div className="link-body"><div className="link-heading"><h2>{link.description}</h2><span className="status status-confirmed">Active</span></div><p>{money(link.amountMinor)} · {link.acceptedAssets.join(", ")}</p><code>swanpay.co/pay/{link.id}</code></div><button className="secondary" onClick={onCopy}>Copy link</button></div>)}</div></>; }
function Analytics({ ledger }: { ledger: Ledger }) { return <><PageHeader title="Analytics" description="Understand volume, conversion, and asset mix." /><section className="stats-grid"><Stat label="Total volume" value={money(ledger.intents.reduce((s, i) => s + BigInt(i.amountMinor), 0n).toString())} trend="+18.4%" /><Stat label="Conversion rate" value="86.2%" trend="+4.8%" /><Stat label="Avg. payment" value={money("65900")} trend="+2.1%" /></section><section className="content-grid"><div className="card chart-card large-chart"><div className="card-heading"><div><h2>Volume over time</h2><p>Payment volume in USD</p></div></div><div className="big-bars">{[32, 45, 28, 59, 51, 70, 63, 81, 75, 92, 84, 96].map((h, i) => <div key={i}><span style={{ height: `${h}%` }} /><small>{["Aug 28", "Sep 1", "Sep 5", "Sep 8"][i % 4]}</small></div>)}</div></div><div className="card asset-card"><div className="card-heading"><div><h2>By asset</h2><p>Successful payments</p></div></div>{[["USDC", "68%", "purple"], ["SOL", "24%", "cyan"], ["USDT", "8%", "pink"]].map(([asset, percent, color]) => <div className="asset-row" key={asset}><span className={`asset-dot ${color}`} /><strong>{asset}</strong><div className="progress"><span style={{ width: percent }} /></div><b>{percent}</b></div>)}</div></section></>; }
function Webhooks({ ledger, onTest }: { ledger: Ledger; onTest: () => void }) { return <><PageHeader title="Webhooks" description="Receive real-time events from SwanPay." action="Send test event" onAction={onTest} /><div className="card endpoint-card"><div className="endpoint-status"><span className="dot green" />Endpoint active</div><code>https://api.northwindlabs.dev/webhooks/swanpay</code><button className="secondary">Edit endpoint</button></div><div className="card table-card"><div className="card-heading"><div><h2>Recent deliveries</h2><p>Latest webhook attempts</p></div></div><div className="table-wrap"><table><thead><tr><th>Event</th><th>Result</th><th>Status</th><th>Delivered</th></tr></thead><tbody>{ledger.deliveries.map((delivery) => <tr key={delivery.id}><td><strong>{delivery.eventType}</strong><small>{delivery.id}</small></td><td><span className={delivery.success ? "status status-confirmed" : "status status-failed"}>{delivery.success ? "Delivered" : "Failed"}</span></td><td>{delivery.statusCode}</td><td>{shortDate(delivery.createdAt)}</td></tr>)}</tbody></table></div></div></>; }
function Settings({ ledger, setLedger, onSave }: { ledger: Ledger; setLedger: React.Dispatch<React.SetStateAction<Ledger>>; onSave: () => void }) { return <><PageHeader title="Settings" description="Configure your workspace and settlement preferences." /><div className="settings-grid"><section className="card settings-card"><h2>Workspace</h2><p>Basic organization details.</p><label>Workspace name<input value={ledger.organization.name} onChange={(e) => setLedger((c) => ({ ...c, organization: { ...c.organization, name: e.target.value } }))} /></label><label>Display currency<select value={ledger.organization.displayCurrency} onChange={(e) => setLedger((c) => ({ ...c, organization: { ...c.organization, displayCurrency: e.target.value as DisplayCurrency } }))}><option>USD</option><option>EUR</option><option>NGN</option></select></label><button className="primary" onClick={onSave}>Save changes</button></section><section className="card settings-card"><h2>Settlement</h2><p>Where confirmed payments are sent.</p><label>Settlement asset<select value={ledger.organization.settlementAsset} onChange={(e) => setLedger((c) => ({ ...c, organization: { ...c.organization, settlementAsset: e.target.value } }))}><option>USDC</option><option>USDT</option><option>SOL</option></select></label><label>Settlement wallet<input value={ledger.organization.settlementWallet} onChange={(e) => setLedger((c) => ({ ...c, organization: { ...c.organization, settlementWallet: e.target.value } }))} /></label><div className="notice">Sandbox funds are simulated and never leave your wallet.</div></section></div></>; }
function Checkout({ intent, onBack, onPay }: { intent: PaymentIntent; onBack: () => void; onPay: () => void }) { const [asset, setAsset] = useState(intent.acceptedAssets[0]); return <div className="checkout-page"><button className="back-button" onClick={onBack}>← Back to payments</button><div className="checkout-card"><div className="checkout-brand"><span className="brand-mark">S</span><strong>SwanPay checkout</strong></div><div className="checkout-amount"><span>Amount due</span><strong>{money(intent.amountMinor, intent.currency)}</strong><small>{intent.description}</small></div><div className="checkout-section"><p className="label">Pay with</p><div className="asset-options">{intent.acceptedAssets.map((item) => <button className={asset === item ? "asset-option selected" : "asset-option"} onClick={() => setAsset(item)} key={item}><span className="coin">{item[0]}</span><span><strong>{item}</strong><small>{item === "USDC" ? "USD Coin" : item === "SOL" ? "Solana" : "Tether"}</small></span><span className="check">{asset === item ? "✓" : ""}</span></button>)}</div></div><div className="checkout-wallet"><span className="wallet-icon">◈</span><div><strong>Sandbox wallet</strong><small>Connect a wallet to continue</small></div><button className="secondary" onClick={() => onPay()}>Connect</button></div><button className="primary full checkout-button" onClick={onPay}>Simulate {asset} payment</button><p className="secure-note">Payments are processed securely on the Solana network.</p></div></div>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" onClick={onClose}><div className="modal" onClick={(e) => e.stopPropagation()}><div className="modal-header"><h2>{title}</h2><button className="close-button" onClick={onClose}>×</button></div>{children}</div></div>; }
